-- AlterTable
ALTER TABLE `fishtype` ADD COLUMN `currency` VARCHAR(191) NOT NULL DEFAULT 'TZS',
    ADD COLUMN `price` DECIMAL(65, 30) NOT NULL DEFAULT 0.0,
    ADD COLUMN `status` VARCHAR(191) NOT NULL DEFAULT 'Pending',
    ADD COLUMN `unitSize` DECIMAL(65, 30) NOT NULL DEFAULT 0.0;
